/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export interface InstantiateMsg {
  owner: Addr;
}
export type ExecuteMsg = {
  lock: {
    duration: number;
  };
} | {
  unlock: {
    lock_id: number;
  };
} | {
  withdraw: {
    amount: string;
    denom: string;
  };
};
export type QueryMsg = {
  get_locks: {};
};
export interface MigrateMsg {
  owner: Addr;
}
export interface GetLockResponse {
  locks: number[];
}