/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.16.5.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./OsmosisLock.client";
export declare namespace contracts {
    const OsmosisLock: {
        OsmosisLockQueryClient: typeof _1.OsmosisLockQueryClient;
        OsmosisLockClient: typeof _1.OsmosisLockClient;
    };
}
//# sourceMappingURL=index.d.ts.map